### ISSUE TITLE
Generate Audio

### ISSUE THREAD

**Issue by Millennium-Heap** [Millennium-Heap/musical-instrument#3]
# Description
This phase involves generating audio signals with the help of SignalGenerator class from the NAudio library. We shall also develop the code to control the volume and frequency of our musical instrument.

## Sub-Feature
- Audio signal generated when mouse pressed and stops when unpressed.
- Control volume trackbar.
- Control frequency trackbar.

## Dependencies
- Winforms #1
- NAudio library

## Milestones
- [x] Generate audio signals using mouse pressed.
- [x] Develop code to control volume trackbar.
- [x] Develop code to control frequency trackbar.

## Member/Members (@Github-Hanlde) (@Email-Id)
- Millennium Singha  (@Millennium-Heap) (millenniumsingha@gmail.com)
