### ISSUE TITLE
Mouse Movement

### ISSUE THREAD

**Issue by Millennium-Heap** [Millennium-Heap/musical-instrument#5]
# Description
In this phase, we shall add a panel over our form to limit and track the mouse-movement over the panel as well as its relative movement to its previous state. We shall also develop codes to control the volume and frequency of our instrument based on our mouse movement.

## Sub-Feature
- Track mouse movement over an added panel to the form.
- Track relative mouse movement over the panel.
- Track changes in volume and frequency with respect to mouse movement (up/down).

## Dependencies
- NAudio
- WinForms #1 
- Generate Audio #3 

## Milestones
- [x] Add a panel to the form and track mouse movement over the panel.
- [x] Develop codes to track relative mouse movement over the panel.
- [x] Develop codes to control changes in volume and frequency with respect to mouse movement.

## Member/Members (@Github-Handle) (@Email-Id)
- Millennium Singha (@Millennium-Heap) (millenniumsingha@gmail.com)
